### ISSUE TITLE
WKhtmlToPDF Error

### ISSUE THREAD

**Issue by mommand** [Attendize/Attendize#396] opened 2018-07-09 06:54 UTC
I am using MocOS High Sierra. I installed the attendize successfully, but when I want to order the a ticket I am getting this error. I also installed wkhtml2pdf package. please help me.
![screen shot 2018-07-09 at 11 18 41 am](https://user-images.githubusercontent.com/4653953/42435021-86d828a0-836a-11e8-826f-19474317d187.png)

**Comment by jeremyquinton** [comment] 2018-07-09 07:03
Hi @mommand are you using the Docker environment provided or are you using your own  development environment?

**Comment by mommand** [comment] 2018-07-09 07:04
Hi, Thanks for the prompt response. @jeremyquinton no I am using my own development environment.

**Comment by jeremyquinton** [comment] 2018-07-09 07:20
@mommand your own development environment is most likely the cause of the issue. I want to check what version of wkhtml2pdf I am running as that might be the cause of the problem. This might be a real bug so would be good to get it fixed if we can.

**Comment by jeremyquinton** [comment] 2018-07-09 07:39
@mommand in your screenshot it looks like the version is 0.12.1 

ok sure in your project in
```
/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/
```
There should be various drivers you can use which can be configured in the .env file 

Here is my version information and I have no issues
```
./vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltopdf-amd64 --version
wkhtmltopdf 0.12.1-c22928d (with patched qt)
```

Can you provide me with some more information about your setup. Are you trying to checkout multiple tickets at once as from the error it looks like there are six pages.

**Comment by mommand** [comment] 2018-07-09 07:42
@jeremyquinton  no I checked out just for one ticket.

**Comment by mommand** [comment] 2018-07-09 07:44
@jeremyquinton I installed the attendize last year and I installed the wkhtm2pdf package yesterday. and how can I update the verstion of package?

**Comment by jeremyquinton** [comment] 2018-07-09 07:51
@mommand the package should be installed  via composer. I am not the original develop of Attendize I just recently started contributing. I see in the composer file that we are using the dev/master for the composer package nitmedia/wkhtml2pdf. 

I might have to update and test this at some point.

**Comment by jeremyquinton** [comment] 2018-07-09 07:58
@mommand in your original screenshot I see there following file is referenced. /Users/797559249.html  If you could upload that file here I can try debug the issue at a later stage.

**Comment by jeremyquinton** [comment] 2018-10-02 16:18
@mommand did you manage to resolve this issue? If you have fixed it can you please close this ticket thanks 

Take a look at the troubleshooting guide if you are still having issues. 
https://www.attendize.com/troubleshooting.html

**Comment by johannac** [comment] 2020-04-20 21:42
This ticket is being closed due to receiving no further response from the original author.

**Closed by johannac** 2020-04-20 21:42 UTC
