### ISSUE TITLE
[BUG] Attendize version 2.0.2 failing to install on MYSQL 5.5/ MYSQL 5.6

### ISSUE THREAD

**Issue by prbt2016** [Attendize/Attendize#805] opened 2020-06-02 10:50 UTC
**Bug description**

Trying to do the manual installation of Attendize version 2.0.2 on MYSQL 5.5/ MYSQL 5.6 throws the following error :

```
 Illuminate\Database\QueryException
 SQLSTATE[HY000]: General error: 1709 Index column size too large. 
The maximum column size is 767 bytes. (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`)) 
```

However script works fine with MYSQL 5.7.

**To Reproduce**

1. Install composer and generate key with artisan key:generate
2. Hit install url http://url/to/attendize/public/install
3. Enter db details etc and click install.
4. The above error is generated.

**Screenshots**

![attendize](https://user-images.githubusercontent.com/17871448/83511299-10d73d80-a4ec-11ea-91d7-6eefb325886c.jpg)

**Environment

**Version of Attendize**
- 2.0.2

**Hosting**
- VPS /Shared-hosting

**OS**
- Centos 6.9 Final

**PHP version**
-PHP 7.3

**Web Server**
-  Apache 2.2.34 .

**Additional context**
Script works fine on MYSQL 5.7.

Could you please check replicate and fix the above issue ocurring with MYSQL 5.5 / MYSQL 5.6. Also what is the minimum required MYSQL version for running Attendize?.

**Comment by johannac** [comment] 2020-06-02 21:10
Hi @prbt2016, thank you for your report. Could you clarify if you tested *both* Mysql 5.5 and Mysql 5.6 and neither work, or if you only tested Mysql 5.5? Laravel requires Mysql 5.6 or higher as indicated [here](https://laravel.com/docs/7.x/database) So if you are testing with Mysql 5.5 it would explain the error.

**Comment by johannac** [comment] 2020-06-02 21:25
I just tested locally with the docker setup using the mysql 5.6 image from docker hub and got the same error, so it appears to be affecting mysql 5.6 too.

**Comment by johannac** [comment] 2020-06-02 22:32
Ok, I have done some more testing with Mysql 5.6. I've found that the problem is that the stated prefix limitation for InnoDB tables in MySQL version 5.6 (and prior versions) is 767 bytes. In Mysql 5.7 and higher it's 3072 bytes, which is why the error doesn't occur there. 

End of support for Mysql 5.6 is listed as February 2021, so although Laravel technically supports it, I don't think we'll try to add support for Attendize at this time. 

If you can, it is preferable to upgrade Mysql to version 5.7 or higher. I will add this to the documentation as a minimum requirement so it's clearer.

If you are unable to upgrade at this time, there is a workaround I've tested locally you can try. In the file `database/migrations/2014_10_12_100000_create_password_resets_table.php` you can either limit the size of the varchar columns like so:
```php
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email', 100)->index();
            $table->string('token', 100)->index();
```
Or you can remove the index all together like so:
```php
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email');
            $table->string('token');
```
Either change works, although restricting the length of the column is probably preferable. 

Hope that helps. I'm going to go ahead and close this as resolved.

**Closed** 2020-06-02 22:33 UTC
Labels: [SOLVED], bug

**Comment by prbt2016** [comment] 2020-06-03 03:35
@johannac Thanks for the kind support. Would upgrade to MYS QL 5.7. Please add it to the documentation regarding MYSQL requirements so that it would be easy for the users.

**Comment by techboycr** [comment] 2020-09-10 22:46
The work around works perfectly!
