### ISSUE TITLE
Invite email not arriving

### ISSUE THREAD

**Issue by justynpride** [Attendize/Attendize#627] opened 2019-04-25 15:20 UTC
I’m trying out the invite attendee email on a clean install. If I select to send ticket with the invite an email is sent as it arrives in my inbox. If I don’t select to send the ticket with the invite then no email arrives in my inbox, or spam folder. I can confirm that all other emails are being send and received through the system ok. Have I missed something?

**Comment by brucealdridge** [comment] 2019-05-23 04:10
@justynpride did you get this solved? I had the same issue and got a bit further - duplicate of #643

**Comment by justynpride** [comment] 2019-05-23 05:40
To be honest I’ve not had a chance to delve into the logs to see what is happening. It was the fact that the invite email with pdf worked, but without pdf didn’t. I’ll try to check the log out.

**Comment by jeremyquinton** [comment] 2019-05-29 14:48
@justynpride 

The checkbox says
```Send invitation & ticket to attendee.```

If its checked the user will receive an invite and an email. 
If its not checked the ticket and attendee are created in the system they just don't get it via email. 

This is not a bug and expected behaviour.

**Closed by jeremyquinton** 2019-05-29 14:48 UTC

**Comment by justynpride** [comment] 2019-05-29 16:46
@jeremyquinton Thanks for the clarification on how it works. It was just different from what I expected with it being 'invite'. It makes sense, and good to understand the system bit more.
