### ISSUE TITLE
What is the status of SCA in attendize?

### ISSUE THREAD

**Issue by Reece0Connor** [Attendize/Attendize#678] opened 2019-08-19 13:34 UTC
What is the status of SCA in attendize? This is approaching fast. Will attendize events be effected immediately/at all?

**Comment by Tuvens** [comment] 2019-08-20 15:30
https://github.com/Attendize/Attendize/issues/665

**Comment by jeremyquinton** [comment] 2019-08-22 06:49
@Reece0Connor closing this as its a duplicate of #665

**Closed by jeremyquinton** 2019-08-22 06:49 UTC
