### ISSUE TITLE
Error when final PDF ticket generation step is reached

### ISSUE THREAD

**Issue by fsciacca** [Attendize/Attendize#438] opened 2018-08-28 18:59 UTC
I feel like I might be perceived as a "wedding crasher," and if so, please let me know. I'm totally enthralled with Attendize and want to use it for events/course registrations for a tiny nonprofit I direct. I've installed it, connected it to my business PayPal account and it appeared to working properly until my first attempt to purchase a ticket. Everything went perfectly, and payment was processed on both the PayPal and my credit card sides. But, I  received an error message "Whoops!, it looks like the server returned an error." after processing the purchase. I receive the same error when I attempt to "Resend Ticket." The error is slightly different when I seek to "Download PDF Ticket, "Whoops, looks like something went wrong."  Here's the deal, I am an older guy (68) with no PHP programming experience. I'm familiar with the computer world pretty well, having cut my teeth on a Mac Plus, working with HyperCard and Resedit back in the day. Using a 1200 baud dialup to access Mac bulletin boards, etc. But...I don't program. This section of GitHub is the only place in the universe working with Attendize. So, I thought I'd ask for help here. If this is inappropriate or foolish, just let me know and I'll disappear. I did this on a wild shot that maybe the fix is known and doable at my end, and someone might be able to help. Thanks.

**Comment by jeremyquinton** [comment] 2018-08-28 19:28
@fsciacca Your issue is most likely related to permissions on your file system or the fact that sending mail is not setup correctly. 

From the document root of your webserver make sure the following folders have the correct permissions. 
Most problems can be fixed my making sure the following files and folders are writable by the web server user

storage/app/
storage/framework/
storage/logs/
storage/cache/
public/user_content/
bootstrap/cache/
.env

always check the log in storage/logs as it will likely show you what the problem is.

The SMTP settings can be configured in the .env file. The example .env file is here. 
https://github.com/Attendize/Attendize/blob/master/.env.example

If emails cannot be sent this should be logged correctly in the log file and a specific error given.

**Comment by fsciacca** [comment] 2018-08-28 20:55
Thank you so much for responding. Most of the messaging features were working before. I adapted the settings for the SMTP as you suggested from the example .env file and afterwards nothing worked. I've reset them back and checked the permissions on the folders you listed. I had already done that during the install. I have two FTP clients that I use, Fetch and Filezilla. Fetch does NOT provide a way to change permissions in subfiles and subdirectories all at once. Filezilla does. Two questions: (1) when you speak of file permissions being set to "write," I show three levels of permissions when I go to edit: Owner, Group, and Others. Should all three of those levels have "write" permission on the list you gave me?  Or just the first two. At present, it's just the first two. And, (2) Do ALL the contents of the folders on that list need to have "write" permission? When I used Filezilla to change permissions on the public/user_content folder, AND gave all subordinates to have "write" permission, there was a noticeable difference in the GUI of the entire program. Right now, it appears that I can do everything except generate tickets. The internal messaging system is working. I can cancel, refund, and message, as well as send CC's to the organizer. But, whenever I seek to Resend or Download anything related to a Ticket, I get the Server error. Does that help?

**Comment by jeremyquinton** [comment] 2018-08-29 06:36
> When you speak of file permissions being set to "write," I show three levels of permissions when I go to edit: Owner, Group, and Others. Should all three of those levels have "write" permission on the list you gave me? Or just the first two. At present, it's just the first two. 

Simple answer is the webserver user needs write permissions. To answer this question properly it depends on how the webserver is configured. Here is a similar question on shared hosts https://superuser.com/questions/380119/permissions-on-a-typical-shared-linux-web-host. 

> And, (2) Do ALL the contents of the folders on that list need to have "write" permission? 

No just the folders need write permissions. 

Please see the troubleshooting guide as it might help you fix your problem. https://github.com/Attendize/Attendize#troubleshooting

**Comment by jeremyquinton** [comment] 2018-09-03 20:13
@fsciacca 

A new documentation website has been launched 

Please see the troubleshooting guide http://www.attendize.com/troubleshooting.html to help you debug your installation. 

Please see manual installation instructions here http://www.attendize.com/getting_started.html#manual-installation

Please see docker installation instructions here 
http://www.attendize.com/getting_started.html#running-attendize-in-docker-for-development 

For now I am going to close this ticket.

**Closed by jeremyquinton** 2018-09-03 20:13 UTC
