### ISSUE TITLE
datetime picker on create event for start date  / end date disappear on  click textbox

### ISSUE THREAD

**Issue by harshit1235** [Attendize/Attendize#625] opened 2019-04-22 11:05 UTC
Hi,

When create event on model start date and end date time picker disappear after few seconds 

Can you please suggest me.

I already commented below link from 5 files but still same issue

$(document).on("click.DateTimePicker", function(e)
{
	//oDTP._hidePicker(""); ---> Comment this line from 5 files in But still same issue
});

 Please help me

**Comment by jeremyquinton** [comment] 2019-05-29 14:50
@harshit1235 this issue is a duplicate of #612 

The date picker is working correctly in master.

**Closed by jeremyquinton** 2019-05-29 14:51 UTC
